--COMMIT e ROLLBACK

SELECT * FROM [dbo].[TABELA DE VENDEDORES]

BEGIN TRANSACTION

update [TABELA DE VENDEDORES]
set [PERCENTUAL COMISSAO] = [PERCENTUAL COMISSAO]*1.15

ROLLBACK



BEGIN TRANSACTION

insert into [TABELA DE VENDEDORES]
(MATRICULA, NOME, [PERCENTUAL COMISSAO],[DATA DE ADMISSAO], FERIAS, BAIRRO) 
VALUES('99999', 'João da Silva', 0.08, '2014-09-01', 0, 'Icaraí')

COMMIT


-- Campo Auto-incremento
-- IDENTITY [(início, incremento)]

create table TESTE
(
	ID INT IDENTITY(1,1) NOT NULL,
	NOME VARCHAR(20) NOT NULL
)

insert into TESTE (NOME)
values ('Roberto Silva')

insert into TESTE (NOME)
values ('André Luiz')

insert into TESTE (NOME)
values ('Jéssica Santos')

select * from TESTE

delete from TESTE
where ID = 1

insert into TESTE (NOME)
values ('Leandro Lima')

drop table teste

create table TESTE
(
	ID INT IDENTITY(100,5) NOT NULL,
	NOME VARCHAR(20) NOT NULL
)

insert into TESTE (NOME)
values ('Roberto Silva')

insert into TESTE (NOME)
values ('André Luiz')

insert into TESTE (NOME)
values ('Jéssica Santos')

insert into TESTE (NOME)
values ('Leandro Lima')

select * from teste


--DEFININDO PADRÕES PARA UM CAMPO
create table TAB_PADRAO
(
	ID int identity(1,1) not null,
	DESCRICAO VARCHAR(20),
	ENDERECO VARCHAR (200),
	CIDADE VARCHAR (50) DEFAULT 'Cidade não definida',
	DATA_CRIACAO DATE DEFAULT GETDATE()
)

INSERT INTO [TAB_PADRAO]
(DESCRICAO, ENDERECO, CIDADE, DATA_CRIACAO)
VALUES ('Pedro Silva', 'Rua 145','São Paulo','2019-09-25')

select * from [dbo].[TAB_PADRAO]

INSERT INTO [TAB_PADRAO]
(DESCRICAO, ENDERECO)
VALUES ('Pedro Silva', 'Rua 245')

select * from [dbo].[TAB_PADRAO]


--TRIGGER
/*
CREATE TRIGGER NOME_DA_TRIGGER
ON [NOME DA TABELA]
[FOR/AFTER/INSTEAD OF] [INSERT/UPDATE/DELETE]

<CORPO DA TRIGGER>
*/

CREATE TABLE [VENDAS DIARIAS]
(
	DATA_VENDA DATE,
	TOTAL_VENDA FLOAT
)

CREATE TRIGGER TG_VENDAS_DIARIAS
ON [TABELA DE ITENS NOTAS FISCAIS]
AFTER INSERT, UPDATE, DELETE
AS
	BEGIN
		DELETE FROM [VENDAS DIARIAS]

		INSERT INTO [VENDAS DIARIAS](DATA_VENDA, TOTAL_VENDA)

		SELECT NF.[DATA],
			   SUM(INF.QUANTIDADE*INF.PREÇO) AS 'TOTAL VENDAS'
		FROM [TABELA DE NOTAS FISCAIS]NF
		INNER JOIN [TABELA DE ITENS NOTAS FISCAIS]INF
		ON NF.NUMERO = INF.NUMERO
		GROUP BY NF.DATA
		ORDER BY NF.DATA DESC
	END

INSERT INTO [TABELA DE NOTAS FISCAIS] (NUMERO,DATA,CPF,MATRICULA,IMPOSTO)
VALUES ('011111', '2021-06-02', '1471156710', '00235', 0.25)

INSERT INTO [TABELA DE ITENS NOTAS FISCAIS] (NUMERO,[CODIGO DO PRODUTO],QUANTIDADE,PREÇO)
VALUES ('011111','1000889', 100,1)

SELECT * FROM [VENDAS DIARIAS]
WHERE YEAR(DATA_VENDA) = 2021

INSERT INTO [TABELA DE ITENS NOTAS FISCAIS] (NUMERO,[CODIGO DO PRODUTO],QUANTIDADE,PREÇO)
VALUES ('011111','1002334', 100,1)

SELECT * FROM [VENDAS DIARIAS]
WHERE YEAR(DATA_VENDA) = 2021

DELETE FROM [TABELA DE ITENS NOTAS FISCAIS]
WHERE NUMERO = '011111' AND [CODIGO DO PRODUTO] = '1002334'

SELECT * FROM [VENDAS DIARIAS]
WHERE YEAR(DATA_VENDA) = 2021

UPDATE [TABELA DE ITENS NOTAS FISCAIS]
SET QUANTIDADE = 300
WHERE NUMERO = '011111' AND [CODIGO DO PRODUTO] = '1000889'

SELECT * FROM [VENDAS DIARIAS]
WHERE YEAR(DATA_VENDA) = 2021

UPDATE [TABELA DE ITENS NOTAS FISCAIS]
SET PREÇO = 5
WHERE NUMERO = '011111' AND [CODIGO DO PRODUTO] = '1000889'

SELECT * FROM [VENDAS DIARIAS]
WHERE YEAR(DATA_VENDA) = 2021

--DESAFIO
SELECT * FROM [TABELA DE CLIENTES]
