CREATE DATABASE ESQUINA_VENDAS

USE ESQUINA_VENDAS

CREATE TABLE [TABELA DE CLIENTES]
(
	[CPF] [VARCHAR] (11) ,
	[NOME] [VARCHAR] (100) ,
	[ENDERECO 1] [VARCHAR] (150) ,
	[ENDERECO 2] [VARCHAR] (150) ,
	[BAIRRO] [VARCHAR] (50) ,
	[CIDADE] [VARCHAR] (50) ,
	[ESTADO] [VARCHAR] (2) ,
	[CEP] [VARCHAR] (8) ,
	[DATA DE NASCIMENTO] [DATE],
	[IDADE] [SMALLINT],
	[SEXO] [VARCHAR] (1) ,
	[LIMITE DE CREDITO] [MONEY] ,
	[VOLUME DE COMPRA] [FLOAT] ,
	[PRIMEIRA COMPRA] [BIT]
)

CREATE TABLE [TABELA DE PRODUTOS]
(
	[CODIGO DO PRODUTO][VARCHAR](10),
	[NOME DO PRODUTO][VARCHAR](50),
	[EMBALAGEM][VARCHAR](20),
	[TAMANHO][VARCHAR](10),
	[SABOR][VARCHAR](20),
	[PREÇO DE LISTA][smallmoney]
)

CREATE TABLE [TABELA DE VENDEDORES]
(
	[MATRICULA][VARCHAR](5),
	[NOME][VARCHAR](100),
	[PERCENTUAL COMISSAO][float]
)




/*INSERINDO DADOS NAS TABELAS.*/

INSERT INTO [TABELA DE VENDEDORES] 
([MATRICULA],[NOME],[PERCENTUAL COMISSAO])
VALUES ('00122','JOABE DA SILVA FREITAS',0.1)

INSERT INTO [TABELA DE PRODUTOS]
([CODIGO DO PRODUTO],[NOME DO PRODUTO],[EMBALAGEM],[TAMANHO],[SABOR],[PREÇO DE LISTA])
VALUES ('1040107','Light-350 ml - Melancia','Lata','350 ml','Melancia', 4.56)

INSERT INTO [TABELA DE PRODUTOS]
([CODIGO DO PRODUTO],[NOME DO PRODUTO],[EMBALAGEM],[TAMANHO],[SABOR],[PREÇO DE LISTA])
VALUES ('1037797','Clean - 2 Litros','PET','2 Litros','Laranja', 16.01)

INSERT INTO [TABELA DE PRODUTOS]
([CODIGO DO PRODUTO],[NOME DO PRODUTO],[EMBALAGEM],[TAMANHO],[SABOR],[PREÇO DE LISTA])
VALUES ('1000889','Sabor da Montanha - 700 ml - Uva','Garrafa','700 ml','Uva', 6.31)

INSERT INTO	[TABELA DE VENDEDORES]
([MATRICULA],[NOME], [PERCENTUAL COMISSAO])
VALUES('00133','Marly dos Santos Gama', 0.08)

INSERT INTO	[TABELA DE VENDEDORES]
([MATRICULA],[NOME], [PERCENTUAL COMISSAO])
VALUES('00144','Bruno César Brandão', 0.05)

INSERT INTO [TABELA DE PRODUTOS]
([CODIGO DO PRODUTO],[NOME DO PRODUTO],[EMBALAGEM],[TAMANHO],[SABOR],[PREÇO DE LISTA])
VALUES ('544931','Frescor do Verão - 350 ml - Limão','PET','350 ml','Limão', 3.20)

INSERT INTO [TABELA DE PRODUTOS]
([CODIGO DO PRODUTO],[NOME DO PRODUTO],[EMBALAGEM],[TAMANHO],[SABOR],[PREÇO DE LISTA])
VALUES ('1078680','Frescor do Verão - 470 ml - Manga','Lata','470 ml','Manga', 5.18)




/*UPDATE - ALTERANDO REGISTROS NAS TABELAS

UPDATE [NOME DA TABELA]
SET [CAMPO/COLUNA A SER ALTERADO] = 'novo valor'
WHERE [CONDIÇÃO]

*/

  UPDATE [TABELA DE PRODUTOS]
  SET [EMBALAGEM] = 'Lata',
	  [PREÇO DE LISTA] = 2.46
  WHERE [CODIGO DO PRODUTO] = '544931'

  UPDATE [TABELA DE PRODUTOS]
  SET [PREÇO DE LISTA] = 2.46
  WHERE [CODIGO DO PRODUTO] = '544931'

  UPDATE [TABELA DE PRODUTOS]
  SET [EMBALAGEM] = 'Garrafa'
  WHERE [CODIGO DO PRODUTO] = '1078680'

 UPDATE [TABELA DE VENDEDORES]
 SET [PERCENTUAL COMISSAO] = 0.11
 WHERE MATRICULA = 00166

 UPDATE [TABELA DE VENDEDORES]
 SET [NOME] = 'Roberta Serra'
 WHERE MATRICULA = 00155




 /*DELETE - EXCLUINDO REGISTROS NAS TABELAS

DELETE FROM [NOME DA TABELA]
WHERE [CONDIÇÃO]

*/

DELETE FROM [TABELA DE PRODUTOS]
WHERE [CODIGO DO PRODUTO] = '1088126'

DELETE FROM [TABELA DE VENDEDORES]
WHERE MATRICULA = '00122'
