/* ALGUMAS FUNÇÕES DO SQL

lower
upper
left
right
replace 
substring
len
concat
trim

*/

-- DESAFIO 1
select NOME, CONCAT(endereco, ' - ', bairro, ' - ', cidade,  ' - ', estado) AS 'ENDEREÇO COMPLETO' 
from [dbo].[TABELA DE CLIENTES]


SELECT SYSDATETIME() AS 'HORA ATUAL'
SELECT GETDATE()

SELECT SYSDATETIMEOFFSET() AS 'HORA & FUSO HORARIO'

SELECT SYSUTCDATETIME() AS 'HORA EM GREENWICH'

SELECT YEAR(GETDATE())
SELECT MONTH(GETDATE())
SELECT DAY(GETDATE())

SELECT DATEDIFF(DAY,'25-08-2015',SYSDATETIME())

SELECT DATEADD (MONTH, 6, GETDATE())
SELECT DATEADD (DAY, 6, GETDATE())
SELECT DATEADD (YEAR, 6, GETDATE())


-- DESAFIO 2
SELECT NOME, DATEDIFF(YEAR, [DATA DE NASCIMENTO],GETDATE()) AS 'IDADE' FROM [TABELA DE CLIENTES]


--DESAFIO 3
select top(5) * from [dbo].[TABELA DE ITENS NOTAS FISCAIS]
select top(5) * from [dbo].[TABELA DE NOTAS FISCAIS]

SELECT 
