--CHECK: Restrição de inserção de dados conforme regra estabelecida na criação da tabela

CREATE TABLE CLIENTE_TESTE
(
	ID INT IDENTITY NOT NULL,
	NOME VARCHAR(20),
	IDADE INT,
	CIDADE VARCHAR(20),
	
	CHECK (IDADE >= 18)
)

INSERT INTO CLIENTE_TESTE (NOME, IDADE, CIDADE) VALUES ('JOAO', 19, 'RIO DE JANEIRO') 

INSERT INTO CLIENTE_TESTE (NOME, IDADE, CIDADE) VALUES ('PEDRO', 21, 'SÃO PAULO')

INSERT INTO CLIENTE_TESTE (NOME, IDADE, CIDADE) VALUES ('MARIA', 17, 'SÃO PAULO')

SELECT * FROM CLIENTE_TESTE

DROP TABLE CLIENTE_TESTE

CREATE TABLE CLIENTE_TESTE
(
	ID INT IDENTITY NOT NULL,
	NOME VARCHAR(20),
	IDADE INT,
	CIDADE VARCHAR(20),
	
	CHECK (IDADE >= 18 AND CIDADE = 'SÃO PAULO')
)

INSERT INTO CLIENTE_TESTE (NOME, IDADE, CIDADE) VALUES ('JOAO', 19, 'RIO DE JANEIRO') 

INSERT INTO CLIENTE_TESTE (NOME, IDADE, CIDADE) VALUES ('PEDRO', 21, 'SÃO PAULO')

INSERT INTO CLIENTE_TESTE (NOME, IDADE, CIDADE) VALUES ('MARIA', 17, 'SÃO PAULO')

SELECT * FROM CLIENTE_TESTE

DROP TABLE CLIENTE_TESTE

CREATE TABLE CLIENTE_TESTE
(
	ID_CLIENTE INT IDENTITY NOT NULL,
	NOME VARCHAR(20),
	IDADE INT,
	CIDADE VARCHAR(20),
	SEXO CHAR(1),
	EMAIL VARCHAR(30)
)

INSERT CLIENTE_TESTE(NOME, IDADE, CIDADE, SEXO, EMAIL) VALUES ('JOSÉ LABORDA', 42, 'CAMPINAS')