-- Desafio
-- Construir uma consulta cujo resultado seja, para cada cliente:
-- 'O cliente Xxxxx Xxxxx faturou XXXXXX no ano de 2016'
-- Obs: Sempre olhar o diagrama entidade-relacionamento para analisar os relacionamentos entre tabelas.

SELECT TOP (1) * FROM [dbo].[TABELA DE CLIENTES]
SELECT TOP (1) * FROM [dbo].[TABELA DE ITENS NOTAS FISCAIS]
SELECT TOP (1) * FROM [dbo].[TABELA DE NOTAS FISCAIS]

SELECT * FROM [dbo].[TABELA DE ITENS NOTAS FISCAIS]INF
INNER JOIN [dbo].[TABELA DE NOTAS FISCAIS]NF
ON INF.NUMERO = NF.NUMERO
INNER JOIN [dbo].[TABELA DE CLIENTES]C
ON C.CPF = NF.CPF


/* Minha Query */
SELECT CONCAT('O cliente ', C.NOME, ' faturou R$ ', format(ROUND(SUM(inf.QUANTIDADE * inf.PREÇO),2), '#,###.##', 'PT-BR'), ' no ano de ', YEAR(NF.DATA)) FROM [dbo].[TABELA DE ITENS NOTAS FISCAIS]INF
INNER JOIN [dbo].[TABELA DE NOTAS FISCAIS]NF
ON INF.NUMERO = NF.NUMERO
INNER JOIN [dbo].[TABELA DE CLIENTES]C
ON C.CPF = NF.CPF
WHERE YEAR(NF.DATA) = 2016
GROUP BY C.NOME, YEAR(NF.DATA)


/* Query do Professor */
SELECT
CONCAT('O cliente ', TC.NOME, ' faturou ',
CONVERT(VARCHAR, CONVERT(DECIMAL(15,2),
SUM(INF.QUANTIDADE * INF.[PREÇO]))), ' no ano ',
CONVERT(VARCHAR, YEAR(NF.DATA))) AS SENTENCA FROM [TABELA DE NOTAS FISCAIS]NF
INNER JOIN [TABELA DE ITENS NOTAS FISCAIS] INF
ON NF.NUMERO = INF.NUMERO
INNER JOIN [TABELA DE CLIENTES] TC
ON NF.CPF = TC.CPF
WHERE YEAR(DATA) = 2016
GROUP BY TC.NOME, YEAR(DATA)


/* AULA 25.05.2021 */

-- NOME(TC), ANO-MÊS(TNF), QUANTIDADE_MÊS, VOLUME DE COMPRAS (TC), STATUS
SELECT TOP (1) * FROM [dbo].[TABELA DE CLIENTES]
SELECT TOP (1) * FROM [dbo].[TABELA DE NOTAS FISCAIS]
SELECT TOP (1) * FROM [dbo].[TABELA DE ITENS NOTAS FISCAIS]


--DESAFIO 1









--DESAFIO 2
-- SABOR(TAB. PRODUTO), ANO(TAB.NOTAS FISCAIS), FATURAMENTO(TAB.ITENS NOTAS FISCAIS_QUANTIDADE*PREÇO), PARTICIPAÇÃO (%)

SELECT TOP(1) * FROM [dbo].[TABELA DE PRODUTOS]
SELECT TOP(1) * FROM [dbo].[TABELA DE NOTAS FISCAIS]
SELECT TOP(1) * FROM [dbo].[TABELA DE ITENS NOTAS FISCAIS]

SELECT SABOR, ANO, QUANTIDADE*PREÇO
















SELECT AUX1.SABOR,AUX1.ANO,ROUND(AUX1.FATURAMENTO,2) FATURAMENTO, CONCAT(ROUND ((AUX1.FATURAMENTO/AUX2.[FATURAMENTO TOTAL 2016])*100,2),' %') PARTICIPACAO
FROM
(SELECT [TABELA DE PRODUTOS].[SABOR], 
	   YEAR ([TABELA DE NOTAS FISCAIS].[DATA]) ANO, 
	   SUM ([TABELA DE ITENS NOTAS FISCAIS].QUANTIDADE*[TABELA DE ITENS NOTAS FISCAIS].PREÇO) FATURAMENTO
FROM [TABELA DE PRODUTOS]
LEFT JOIN [TABELA DE ITENS NOTAS FISCAIS] ON [TABELA DE ITENS NOTAS FISCAIS].[CODIGO DO PRODUTO]=[TABELA DE PRODUTOS].[CODIGO DO PRODUTO]
LEFT JOIN [TABELA DE NOTAS FISCAIS] ON [TABELA DE NOTAS FISCAIS].NUMERO=[TABELA DE ITENS NOTAS FISCAIS].NUMERO
WHERE YEAR ([TABELA DE NOTAS FISCAIS].[DATA])=2016
GROUP BY [TABELA DE PRODUTOS].[SABOR],YEAR ([TABELA DE NOTAS FISCAIS].[DATA])
) AUX1
JOIN 
(SELECT 
	   YEAR ([TABELA DE NOTAS FISCAIS].[DATA]) ANO, 
	   SUM ([TABELA DE ITENS NOTAS FISCAIS].QUANTIDADE*[TABELA DE ITENS NOTAS FISCAIS].PREÇO) [FATURAMENTO TOTAL 2016]
FROM [TABELA DE PRODUTOS]
LEFT JOIN [TABELA DE ITENS NOTAS FISCAIS] ON [TABELA DE ITENS NOTAS FISCAIS].[CODIGO DO PRODUTO]=[TABELA DE PRODUTOS].[CODIGO DO PRODUTO]
LEFT JOIN [TABELA DE NOTAS FISCAIS] ON [TABELA DE NOTAS FISCAIS].NUMERO=[TABELA DE ITENS NOTAS FISCAIS].NUMERO
WHERE YEAR ([TABELA DE NOTAS FISCAIS].[DATA])=2016
GROUP BY YEAR ([TABELA DE NOTAS FISCAIS].[DATA])) AUX2 ON AUX2.ANO = AUX1.ANO
ORDER BY AUX1.FATURAMENTO DESC
