/*Crie uma consulta que traga o faturamento total dos sábados e domingos de cada ano */

SELECT DATENAME(MONTH, NF.[DATA]) AS 'MÊS',
       YEAR(NF.[DATA]) AS 'ANO',
       --YEAR(NF.[DATA]) AS 'ANO',
       DATENAME(WEEKDAY, NF.[DATA]) AS 'FINAL DE SEMANA',
	   FORMAT(SUM(INF.QUANTIDADE*INF.PRECO), 'C', 'PT-BR') AS 'FATURAMENTO'
FROM [TABELA DE NOTAS FISCAIS]NF
INNER JOIN [TABELA DE ITENS NOTAS FISCAIS]INF
ON NF.NUMERO = INF.NUMERO
WHERE DATENAME(WEEKDAY, NF.[DATA]) = 'Sábado' OR DATENAME(WEEKDAY, NF.[DATA]) = 'Domingo'
GROUP BY DATENAME(WEEKDAY, NF.[DATA]), DATENAME(MONTH, NF.[DATA]), YEAR(NF.[DATA])
ORDER BY 1, 2, 3 DESC
GO

SELECT CONCAT(SUBSTRING(CONVERT(VARCHAR, DATENAME(MONTH, NF.[DATA])), 1, 3), ' ', YEAR(NF.[DATA])) AS 'ANO/MES',
       --YEAR(NF.[DATA]) AS 'ANO',
       DATENAME(WEEKDAY, NF.[DATA]) AS 'FINAL DE SEMANA',
	   FORMAT(SUM(INF.QUANTIDADE*INF.PRECO), 'C', 'PT-BR') AS 'FATURAMENTO'
FROM [TABELA DE NOTAS FISCAIS]NF
INNER JOIN [TABELA DE ITENS NOTAS FISCAIS]INF
ON NF.NUMERO = INF.NUMERO
WHERE DATENAME(WEEKDAY, NF.[DATA]) = 'Sábado' OR DATENAME(WEEKDAY, NF.[DATA]) = 'Domingo'
GROUP BY CONCAT(SUBSTRING(CONVERT(VARCHAR, DATENAME(MONTH, NF.[DATA])), 1, 3), ' ', YEAR(NF.[DATA])), DATENAME(WEEKDAY, NF.[DATA])
ORDER BY 1, 2 DESC
GO
