-- 26.08.2021 - Aula 09 (parte 4) - Juntando tabelas
/*1 - Abaixo temos uma amostra de registro de um relatório de faturamento com imposto. 
      Crie este relatório na base de dados Esquina_Vendas. Depois através deste relatório criado. 
	  Mostre apenas o máximo de faturamento com imposto por embalagem.*/

-- Relatório com valor de faturamento com imposto/tipo de embalagem por nota.
SELECT NF.NUMERO, 
	   P.EMBALAGEM, 
	   SUM(INF.QUANTIDADE*INF.PRECO) AS 'FATURAMENTO',
	   SUM(((INF.QUANTIDADE*INF.PRECO) + (INF.QUANTIDADE*INF.PRECO*NF.IMPOSTO))) AS 'FATURAMENTO COM IMPOSTO'
FROM [TABELA DE NOTAS FISCAIS]NF
INNER JOIN [TABELA DE ITENS NOTAS FISCAIS]INF
ON NF.NUMERO = INF.NUMERO
INNER JOIN [TABELA DE PRODUTOS]P
ON INF.[CODIGO DO PRODUTO] = P.[CODIGO DO PRODUTO]
GROUP BY NF.NUMERO, P.EMBALAGEM
ORDER BY 1
GO

/* CÁLCULOS EXTRAS
-- Relatório com valor de faturamento com imposto/tipo de embalagem
SELECT P.EMBALAGEM, 
	   SUM(INF.QUANTIDADE*INF.PRECO) AS 'FATURAMENTO',
	   SUM(((INF.QUANTIDADE*INF.PRECO) + (INF.QUANTIDADE*INF.PRECO*NF.IMPOSTO))) AS 'FATURAMENTO COM IMPOSTO'
FROM [TABELA DE NOTAS FISCAIS]NF
INNER JOIN [TABELA DE ITENS NOTAS FISCAIS]INF
ON NF.NUMERO = INF.NUMERO
INNER JOIN [TABELA DE PRODUTOS]P
ON INF.[CODIGO DO PRODUTO] = P.[CODIGO DO PRODUTO]
GROUP BY P.EMBALAGEM
ORDER BY 1
GO

-- Relatório com valor imposto/tipo de embalagem
SELECT P.EMBALAGEM, 
	   SUM(INF.QUANTIDADE*INF.PRECO) AS 'FATURAMENTO',
	   SUM(INF.QUANTIDADE*INF.PRECO*NF.IMPOSTO) AS 'IMPOSTO'
FROM [TABELA DE NOTAS FISCAIS]NF
INNER JOIN [TABELA DE ITENS NOTAS FISCAIS]INF
ON NF.NUMERO = INF.NUMERO
INNER JOIN [TABELA DE PRODUTOS]P
ON INF.[CODIGO DO PRODUTO] = P.[CODIGO DO PRODUTO]
GROUP BY P.EMBALAGEM
ORDER BY 1
GO
*/