select * from [TABELA DE CLIENTES]
go

select * from [TABELA DE VENDEDORES]
go

-- INNER JOIN: traz o que há em comum.
SELECT V.NOME AS 'NOME_VEND', V.BAIRRO AS 'BAIRRO_VEND', C.BAIRRO AS 'BAIRRO_CLIENTE', C.NOME AS 'NOME_CLIENTE'
FROM [TABELA DE VENDEDORES]V INNER JOIN [TABELA DE CLIENTES]C
ON C.BAIRRO = V.BAIRRO
GO

-- LEFT JOIN: traz todos os registros da tabela da esquerda, mesmo que não haja correspondência na tabela da direita.
-- Nesse caso, trará todos os vendedores.
SELECT V.NOME AS 'NOME_VEND', V.BAIRRO AS 'BAIRRO_VEND', C.BAIRRO AS 'BAIRRO_CLIENTE', C.NOME AS 'NOME_CLIENTE'
FROM [TABELA DE VENDEDORES]V LEFT JOIN [TABELA DE CLIENTES]C
ON C.BAIRRO = V.BAIRRO
GO

-- RIGHT JOIN: traz todos os registros da tabela da direita, mesmo que não haja correspondência na tabela da esquerda.
-- Nesse caso, trará todos os clientes.
SELECT V.NOME AS 'NOME_VEND', V.BAIRRO AS 'BAIRRO_VEND', C.BAIRRO AS 'BAIRRO_CLIENTE', C.NOME AS 'NOME_CLIENTE'
FROM [TABELA DE VENDEDORES]V RIGHT JOIN [TABELA DE CLIENTES]C
ON C.BAIRRO = V.BAIRRO
ORDER BY V.NOME 
GO

-- FULL JOIN: traz todos os registros de ambas tabelas mesmo sem correspondência.
SELECT V.NOME AS 'NOME_VEND', V.BAIRRO AS 'BAIRRO_VEND', C.BAIRRO AS 'BAIRRO_CLIENTE', C.NOME AS 'NOME_CLIENTE'
FROM [TABELA DE VENDEDORES]V FULL JOIN [TABELA DE CLIENTES]C
ON C.BAIRRO = V.BAIRRO
GO

-- CROSS JOIN: faz uma análise combinatória.
SELECT V.NOME AS 'NOME_VEND', V.BAIRRO AS 'BAIRRO_VEND', C.BAIRRO AS 'BAIRRO_CLIENTE', C.NOME AS 'NOME_CLIENTE'
FROM [TABELA DE VENDEDORES]V CROSS JOIN [TABELA DE CLIENTES]C
GO
