/* Crie uma consulta que mostre o nome do vendedor, o número da nota fiscal, o valor faturado da nota
e quanto o vendedor  ganhou de comissão para cada nota fiscal.
*/
USE ESQUINA_VENDAS
GO

SELECT TOP 1 * FROM [TABELA DE VENDEDORES]
GO

SELECT TOP 1 * FROM [TABELA DE NOTAS FISCAIS]
GO

SELECT COUNT(*) FROM [TABELA DE NOTAS FISCAIS]  -- 87877 registros.
GO

SELECT TOP 1 * FROM [TABELA DE ITENS NOTAS FISCAIS]
GO

SELECT COUNT(*) FROM [TABELA DE ITENS NOTAS FISCAIS]
GO


SELECT V.NOME AS 'VENDEDOR',
	   NF.NUMERO AS 'Nº DA NF', 
	   INF.QUANTIDADE*INF.PRECO AS 'TOTAL', 
	   V.[PERCENTUAL COMISSAO]*INF.QUANTIDADE*INF.PRECO AS 'COMISSÃO'
FROM [TABELA DE VENDEDORES]V
INNER JOIN [TABELA DE NOTAS FISCAIS]NF
ON V.MATRICULA = NF.MATRICULA
INNER JOIN [TABELA DE ITENS NOTAS FISCAIS]INF
ON NF.NUMERO = INF.NUMERO
GO

SELECT V.NOME AS 'VENDEDOR',
	   NF.NUMERO AS 'Nº DA NF', 
	   ROUND(SUM(INF.QUANTIDADE*INF.PRECO), 2) AS 'TOTAL', 
	   ROUND(SUM(V.[PERCENTUAL COMISSAO]*INF.QUANTIDADE*INF.PRECO), 2) AS 'COMISSÃO'
FROM [TABELA DE VENDEDORES]V
INNER JOIN [TABELA DE NOTAS FISCAIS]NF
ON V.MATRICULA = NF.MATRICULA
INNER JOIN [TABELA DE ITENS NOTAS FISCAIS]INF
ON NF.NUMERO = INF.NUMERO
GROUP BY V.NOME, NF.NUMERO
ORDER BY NF.NUMERO
GO

/* Crie uma consulta que traga como resultado a quantidade de vendas no mês de Dezembro de 2015
somente para os clientes do bairro da Tijuca.*/
SELECT TOP 1 * FROM [TABELA DE NOTAS FISCAIS]
GO

SELECT TOP 1 * FROM [TABELA DE CLIENTES]
GO

SELECT CPF FROM [TABELA DE CLIENTES]  -- 3 REGISTROS
WHERE BAIRRO = 'Tijuca'
GO

SELECT C.NOME, C.CPF, C.BAIRRO, NF.DATA, NF.NUMERO FROM [TABELA DE CLIENTES]C
INNER JOIN [TABELA DE NOTAS FISCAIS]NF
ON C.CPF = NF.CPF
WHERE NF.DATA BETWEEN '20151201' AND '20151231'
GO

SELECT Z.NOME, Z.CPF, COUNT(Z.NUMERO) AS 'TOTAL DE NOTAS'
FROM (SELECT C.NOME, C.CPF, C.BAIRRO, NF.DATA, NF.NUMERO 
      FROM [TABELA DE CLIENTES]C
      INNER JOIN [TABELA DE NOTAS FISCAIS]NF
	  ON C.CPF = NF.CPF
	  WHERE NF.DATA BETWEEN '20151201' AND '20151231')Z
WHERE Z.CPF IN (SELECT CPF FROM [TABELA DE CLIENTES]
                WHERE BAIRRO = 'Tijuca')
GROUP BY Z.NOME, Z.CPF
GO

SELECT C.NOME, NF.CPF, COUNT(NF.NUMERO) AS 'TOTAL DE NOTAS' FROM [TABELA DE NOTAS FISCAIS]NF
INNER JOIN [TABELA DE CLIENTES]C
ON C.CPF = NF.CPF
WHERE DATA BETWEEN '20151201' AND '20151231'
GROUP BY C.NOME, NF.CPF
HAVING NF.CPF IN (SELECT CPF FROM [TABELA DE CLIENTES]
                WHERE BAIRRO = 'Tijuca')
GO

