-- Formatação de Hora:Minutos:Segundos para o Getdate()
select format(cast(getdate() as datetime), 'HH:mm:ss') as 'time'
go

create table vendas_diarias(
	data_venda date,
	total_venda float
)
go

create trigger tg_vendas_diarias
on [TABELA DE ITENS NOTAS FISCAIS]
after insert, update, delete
as
begin

	delete from vendas_diarias
	insert into vendas_diarias(data_venda,total_venda)

	SELECT NF.DATA, SUM(INF.QUANTIDADE*INF.PRECO) AS 'TOTAL VENDA'
	FROM [TABELA DE ITENS NOTAS FISCAIS]INF
	INNER JOIN [TABELA DE NOTAS FISCAIS]NF
	ON INF.NUMERO = NF.NUMERO
	GROUP BY NF.DATA
	ORDER BY NF.DATA DESC
end
go

-- TESTANDO GATILHO TG_VENDAS_DIARIAS
INSERT INTO [TABELA DE NOTAS FISCAIS] (NUMERO, DATA, CPF, MATRICULA, IMPOSTO)
VALUES ('87977', '2021-09-15', '1471156710', '00235', 0.25)
GO

INSERT INTO [TABELA DE NOTAS FISCAIS] (NUMERO, DATA, CPF, MATRICULA, IMPOSTO)
VALUES ('87978', '2021-09-16', '1471156710', '00235', 0.25)
GO

INSERT INTO [TABELA DE ITENS NOTAS FISCAIS] (NUMERO, [CODIGO DO PRODUTO], QUANTIDADE, PRECO)
VALUES ('87977', '1000889',  100, 1)
GO

-- VERIFICANDO NA TABELA DE VENDAS_DIÁRIAS
SELECT * FROM [vendas_diarias]
WHERE YEAR(data_venda) = 2021
GO

INSERT INTO [TABELA DE ITENS NOTAS FISCAIS] (NUMERO, [CODIGO DO PRODUTO], QUANTIDADE, PRECO)
VALUES ('87977', '1000889',  100, 1)
GO

INSERT INTO [TABELA DE ITENS NOTAS FISCAIS] (NUMERO, [CODIGO DO PRODUTO], QUANTIDADE, PRECO)
VALUES ('87977', '1002334',  500, 1)
GO

SELECT * FROM [vendas_diarias]
WHERE YEAR(data_venda) = 2021
GO

INSERT INTO [TABELA DE ITENS NOTAS FISCAIS] (NUMERO, [CODIGO DO PRODUTO], QUANTIDADE, PRECO)
VALUES ('87978', '1002767',  50, 2)
GO

SELECT * FROM [vendas_diarias]
WHERE YEAR(data_venda) = 2021
GO

INSERT INTO [TABELA DE NOTAS FISCAIS] (NUMERO, DATA, CPF, MATRICULA, IMPOSTO)
VALUES ('87979', '2021-09-16', '1471156710', '00235', 0.25)
GO

INSERT INTO [TABELA DE ITENS NOTAS FISCAIS] (NUMERO, [CODIGO DO PRODUTO], QUANTIDADE, PRECO)
VALUES ('87979', '1004327', 200, 3)
GO

SELECT * FROM [vendas_diarias]
WHERE YEAR(data_venda) = 2021
GO

SELECT * FROM [TABELA DE ITENS NOTAS FISCAIS]
WHERE NUMERO = '87977'
GO

BEGIN TRANSACTION

DELETE FROM [TABELA DE ITENS NOTAS FISCAIS]
WHERE NUMERO = '87977' AND [CODIGO DO PRODUTO] = '1002334'
GO

COMMIT
GO

BEGIN TRANSACTION

UPDATE [TABELA DE ITENS NOTAS FISCAIS]
SET [QUANTIDADE] = 200
WHERE NUMERO = '87977'
GO

COMMIT
GO

-- DESAFIO - AULA 16
-- CONSTRUA UMA TRIGGER, DE NOME TG_CLIENTES_IDADE, QUE ATUALIZE AS IDADES DOS CLIENTES, NA TABELA DE CLIENTES, TODA VEZ QUE A 
-- TABELA SOFRER UMA INCLUSÃO. ALTERAÇÃO OU EXCLUSÃO.
-- OBS: VAI GERAR UMA NOVA COLUNA DE NOME IDADE

SELECT * FROM [TABELA DE CLIENTES]
GO

SELECT CPF, IDADE, [DATA DE NASCIMENTO], DATEDIFF(YEAR, [DATA DE NASCIMENTO], GETDATE()) AS 'IDADE ATUAL'
FROM [TABELA DE CLIENTES]
GO

CREATE TRIGGER TG_CLIENTE_IDADE
ON [TABELA DE CLIENTES]
AFTER INSERT, UPDATE, DELETE
AS
BEGIN
	UPDATE [TABELA DE CLIENTES]
	SET IDADE = DATEDIFF(YEAR, [DATA DE NASCIMENTO], GETDATE())
END
GO