------------------ALTER TABLE-----------------------------------------------


/* CREATE TABLE */
CREATE TABLE PRODUTO
(
	IDPRODUTO INT IDENTITY NOT NULL,
	DESCRICAO VARCHAR(30) NOT NULL,
	PRECO FLOAT NOT NULL,
)

--Para adicionar uma coluna em uma tabela, use a seguinte sintaxe: 
ALTER TABLE PRODUTO
ADD FRETE FLOAT NULL



SELECT * FROM PRODUTO 

--Para excluir uma coluna em uma tabela, use a seguinte sintaxe (observe que alguns sistemas de banco de dados não permitem a exclusão de uma coluna): 
ALTER TABLE PRODUTO
DROP COLUMN FRETE


SELECT * FROM PRODUTO 

-- Para alterar o tipo de dados de uma coluna em uma tabela, use a seguinte sintaxe: 
ALTER TABLE PRODUTO
ALTER COLUMN FRETE DECIMAL(10,2)


-- Incluir constraint e excluir
ALTER TABLE [CLIENTE_TESTE]
	ADD CONSTRAINT PK_ID PRIMARY KEY (ID_CLIENTE)

ALTER TABLE [CLIENTE_TESTE]
	ADD CONSTRAINT FK_CLIENTE_TESTE_TABELA_DE_NOTAS_FISCAIS FOREIGN KEY  (NUMERO) REFERENCES [TABELA DE NOTAS FISCAIS] (NUMERO)


ALTER TABLE CLIENTE_TESTE
	DROP  CONSTRAINT PK_ID

ALTER TABLE CLIENTE_TESTE
	DROP CONSTRAINT FK_CLIENTE_TESTE_TABELA_DE_NOTAS_FISCAIS


/* ACRESCENTAR UMA COLUNA */
ALTER TABLE [NOME DA TABELA]
ADD [NOME DA COLUNA] <TIPO>

/* EXCLUIR COLUNA */
ALTER TABLE [NOME DA TABELA]
DROP [NOME DA COLUNA]

/* ALTERAR COLUNA*/
ALTER TABLE [NOME DA TABELA]
ALTER COLUMN [NOME DA COLUNA] <TIPO>

/* INCLUIR CONSTRAINT - PRIMARY KEY*/
ALTER TABLE [NOME DA TABELA]
	ADD CONSTRAINT [NOME DA CONSTRAINT] PRIMARY KEY ([NOME DO CAMPO])

/* INCLUINDO CHAVE ESTRANGEIRA - FOREIGN KEY*/
ALTER TABLE [NOME DA TABELA]
	ADD CONSTRAINT [NOME DA CONSTRAINT] FOREIGN KEY  ([NOME DO CAMPO]) REFERENCES [TABELA DE REFERÊNCIA] ([NOME DO CAMPO REFERENTE])

/* EXCLUIR CONSTRAINT - PRIMARY KEY*/
ALTER TABLE [NOME DA TABELA]
	DROP  CONSTRAINT [NOME DA CONSTRAINT]