USE [ESQUINA_VENDAS]
GO

select * from [TABELA DE PRODUTOS]
GO

select embalagem, tamanho, sabor from [TABELA DE PRODUTOS]
GO

select distinct embalagem, tamanho from [TABELA DE PRODUTOS]
GO

select distinct embalagem, tamanho, sabor
from [TABELA DE PRODUTOS]
where sabor like '%Maça%'
GO

/* ESTRUTURA DE UMA VARIÁVEL NO T-SQL
DECLARE @NOME_DA_VARIAVEL [TIPO DA VARIÁVEL] (TAMANHO)
SET @NOME_DA_VARIAVEL = 'VALOR DA VARIAVEL'
SELECT @NOME_DA_VARIAVEL AS 'APELIDO PARA A VARIAVEL'
*/

DECLARE @TESTE1 VARCHAR (20) -- A PALAVRA RESERVADA DECLARE SERVE PARA CRIAR A VARIÁVEL
SET @TESTE1 = 'SQL SERVER' -- A PALAVRA RESERVADA SET É PARA ATRIBUIR VALORES PARA AS VARIÁVEIS
SELECT @TESTE1 AS 'PRIMEIRO TESTE' -- A PALAVRA RESERVADA SELECT É PARA PROJETAR A VARIÁVEL E SEU RESPECTIVO VALOR NO PAINEL DE MENSAGEM
GO

DECLARE @RESPOSTA VARCHAR (30)
DECLARE @VALOR INT

SET @VALOR = 3

IF @VALOR = 3
	PRINT 'VALOR MENOR QUE 10'
ELSE
	PRINT 'VALOR MAIOR QUE 10'
GO

-- T-SQL
/*
	BEGIN
		CORPO DO BLOCO
	END
	GO
*/

DECLARE @CONTADOR INT
SET @CONTADOR = 0

WHILE @CONTADOR < 6
BEGIN
	PRINT @CONTADOR
	SET @CONTADOR = @CONTADOR + 1
END
GO






