/* Minha Query */
SELECT CONCAT('O cliente ', C.NOME, ' faturou R$ ', format(ROUND(SUM(inf.QUANTIDADE * inf.PREÇO),2), '#,###.##', 'PT-BR'), ' no ano de ', YEAR(NF.DATA)) FROM [dbo].[TABELA DE ITENS NOTAS FISCAIS]INF
INNER JOIN [dbo].[TABELA DE NOTAS FISCAIS]NF
ON INF.NUMERO = NF.NUMERO
INNER JOIN [dbo].[TABELA DE CLIENTES]C
ON C.CPF = NF.CPF
WHERE YEAR(NF.DATA) = 2016
GROUP BY C.NOME, YEAR(NF.DATA)