-- 1 - Crie uma consulta que mostre o nome do vendedor, o número da nota fiscal, o valor faturado da nota e quanto o vendedor
--     ganhou de comissão para cada nota fiscal. Mandar o arquivo em (.sql) com o seu nome conforme exemplo: nome_do_aluno.sql

SELECT TOP(1) * FROM [TABELA DE VENDEDORES]
SELECT TOP(1) * FROM [TABELA DE NOTAS FISCAIS]
SELECT TOP(1) * FROM [TABELA DE ITENS NOTAS FISCAIS]

SELECT V.NOME, NF.NUMERO, INF.QUANTIDADE*INF.PREÇO, V.[PERCENTUAL COMISSAO]*INF.QUANTIDADE*INF.PREÇO FROM [TABELA DE VENDEDORES]V
INNER JOIN [TABELA DE NOTAS FISCAIS]NF
ON V.MATRICULA = NF.MATRICULA
INNER JOIN [TABELA DE ITENS NOTAS FISCAIS]INF
ON NF.NUMERO = INF.NUMERO

SELECT V.NOME, 
	   NF.NUMERO AS 'Nº DA NF',
	   SUM(INF.QUANTIDADE*INF.PREÇO) AS 'VALOR FATURADO',
	   SUM(V.[PERCENTUAL COMISSAO]*INF.QUANTIDADE*INF.PREÇO) AS 'COMISSÃO (R$)'
FROM [TABELA DE VENDEDORES]V
INNER JOIN [TABELA DE NOTAS FISCAIS]NF
ON V.MATRICULA = NF.MATRICULA
INNER JOIN [TABELA DE ITENS NOTAS FISCAIS]INF
ON NF.NUMERO = INF.NUMERO
GROUP BY V.NOME, NF.NUMERO
ORDER BY SUM(V.[PERCENTUAL COMISSAO]*INF.QUANTIDADE*INF.PREÇO)

--QUERY FINAL
SELECT V.NOME, 
	   NF.NUMERO AS 'Nº DA NF',
	   FORMAT(SUM(INF.QUANTIDADE*INF.PREÇO), 'R$ ##.##') AS 'VALOR FATURADO',
	   FORMAT(SUM(V.[PERCENTUAL COMISSAO]*INF.QUANTIDADE*INF.PREÇO), 'R$ ##.##') AS 'COMISSÃO (R$)'
FROM [TABELA DE VENDEDORES]V
INNER JOIN [TABELA DE NOTAS FISCAIS]NF
ON V.MATRICULA = NF.MATRICULA
INNER JOIN [TABELA DE ITENS NOTAS FISCAIS]INF
ON NF.NUMERO = INF.NUMERO
GROUP BY V.NOME, NF.NUMERO
ORDER BY SUM(V.[PERCENTUAL COMISSAO]*INF.QUANTIDADE*INF.PREÇO)

