/* Na aula 11 (Exemplos de relatórios) temos o "Relatório de vendas percentual por sabor". 
Crie uma função que ao inserir o tipo de embalagem a função retorne uma tabela com todos os anos, seu faturamento e a participação em percentual. */


---CONSULTA
SELECT * FROM
(SELECT AUX1.EMBALAGEM, AUX1.ANO, FORMAT(AUX1.FATURAMENTO,'C','PT-BR') AS 'FATURAMENTO', CONVERT(VARCHAR,ROUND((AUX1.FATURAMENTO/AUX2.[FATURAMENTO ANUAL])*100,2))+' %' AS 'PERCENTUAL' FROM
(SELECT TP.EMBALAGEM, YEAR (NF.DATA) AS 'ANO', SUM (INF.QUANTIDADE * INF.PREÇO) AS 'FATURAMENTO' FROM [TABELA DE ITENS NOTAS FISCAIS]INF
INNER JOIN [TABELA DE NOTAS FISCAIS]NF
ON INF.NUMERO = NF.NUMERO
INNER JOIN [TABELA DE PRODUTOS]TP
ON INF.[CODIGO DO PRODUTO] = TP.[CODIGO DO PRODUTO]
GROUP BY TP.EMBALAGEM, YEAR (NF.DATA))AUX1
INNER JOIN (SELECT  YEAR (NF.DATA) AS 'ANO', SUM (INF.QUANTIDADE * INF.PREÇO) AS 'FATURAMENTO ANUAL' FROM [TABELA DE ITENS NOTAS FISCAIS]INF
INNER JOIN [TABELA DE NOTAS FISCAIS]NF
ON INF.NUMERO = NF.NUMERO
INNER JOIN [TABELA DE PRODUTOS]TP
ON INF.[CODIGO DO PRODUTO] = TP.[CODIGO DO PRODUTO]
GROUP BY YEAR (NF.DATA))AUX2
ON AUX1.ANO = AUX2.ANO)AUX3
WHERE AUX3.EMBALAGEM = 'Lata'

---CRIAR A FUNÇÃO

CREATE FUNCTION [dbo].[FuncFaturamentoPercentual] (@EMBALAGEM VARCHAR (50), @FATURAMENTO FLOAT, @PERCENTUAL FLOAT, @ANO DATE) RETURNS TABLE
AS
	RETURN
		SELECT AUX1.EMBALAGEM,AUX1.ANO,ROUND(AUX1.[FATURAMENTO],2) AS 'FATURAMENTO', CONVERT (VARCHAR,ROUND((AUX1.[FATURAMENTO]/AUX2.[FATURAMENTO_ANUAL])*100,2))+ '%' AS 'PERCENTUAL' FROM
		(SELECT TP.[EMBALAGEM], YEAR(NF.DATA) AS 'ANO',SUM (INF.QUANTIDADE*INF.PREÇO) AS 'FATURAMENTO' FROM [TABELA DE ITENS NOTAS FISCAIS]INF
			INNER JOIN [TABELA DE NOTAS FISCAIS]NF
			ON INF.NUMERO = NF.NUMERO 
			INNER JOIN [TABELA DE PRODUTOS]TP
			ON INF.[CODIGO DO PRODUTO] = TP.[CODIGO DO PRODUTO] 
		GROUP BY TP.EMBALAGEM,YEAR(NF.DATA))AUX1
			INNER JOIN
			(SELECT YEAR(NF.DATA) AS 'ANO',SUM (INF.QUANTIDADE*INF.PREÇO) AS 'FATURAMENTO_ANUAL' FROM [TABELA DE ITENS NOTAS FISCAIS]INF
			INNER JOIN [TABELA DE NOTAS FISCAIS]NF
			ON INF.NUMERO = NF.NUMERO 
			INNER JOIN [TABELA DE PRODUTOS]TP
			ON INF.[CODIGO DO PRODUTO] = TP.[CODIGO DO PRODUTO]
		GROUP BY YEAR(NF.DATA))AUX2
			ON AUX1.ANO = AUX2.ANO
			WHERE AUX1.EMBALAGEM = 'PET'